//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitricStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CitricStoreEntities5 : DbContext
    {
        public CitricStoreEntities5()
            : base("name=CitricStoreEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APP> APPs { get; set; }
        public virtual DbSet<BANK> BANKs { get; set; }
        public virtual DbSet<GAME> GAMEs { get; set; }
        public virtual DbSet<HEDIEUHANH> HEDIEUHANHs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<NGONNGU> NGONNGUs { get; set; }
        public virtual DbSet<NHAPHATHANH> NHAPHATHANHs { get; set; }
        public virtual DbSet<ORDER_INFO> ORDER_INFO { get; set; }
        public virtual DbSet<ORDER_PRODUCT> ORDER_PRODUCT { get; set; }
        public virtual DbSet<OVERALL> OVERALLs { get; set; }
        public virtual DbSet<THELOAI> THELOAIs { get; set; }
        public virtual DbSet<THELOAIAPP> THELOAIAPPs { get; set; }
        public virtual DbSet<THELOAIGAME> THELOAIGAMEs { get; set; }
    }
}
