//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitricStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER_INFO()
        {
            this.ORDER_PRODUCT = new HashSet<ORDER_PRODUCT>();
        }
    
        public int IDOrder { get; set; }
        public System.DateTime DateOrder { get; set; }
        public int IDCus { get; set; }
        public string NameOrder { get; set; }
        public string PhoneOrder { get; set; }
        public string EmailOrder { get; set; }
        public int IDBank { get; set; }
        public string IDPayAccount { get; set; }
        public string NamePayAccount { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> IDSttOrder { get; set; }
    
        public virtual BANK BANK { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual ORDER_STATUS ORDER_STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_PRODUCT> ORDER_PRODUCT { get; set; }
    }
}
