//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitricStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OVERALL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OVERALL()
        {
            this.ORDER_PRODUCT = new HashSet<ORDER_PRODUCT>();
        }
    
        public int IDOverall { get; set; }
        public string NameOverall { get; set; }
        public string Description { get; set; }
        public string Capacity { get; set; }
        public Nullable<int> IDCat { get; set; }
        public Nullable<int> IDPublisher { get; set; }
        public Nullable<int> IDPlatform { get; set; }
        public Nullable<int> IDLanguage { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Rating { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string PicBG { get; set; }
        public string PicDetail1 { get; set; }
        public string PicDetail2 { get; set; }
        public string PicDetail3 { get; set; }
        public string PicDetail4 { get; set; }
        public string SoftOrGame { get; set; }
        public string LinkTai { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual LANGUAGE LANGUAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_PRODUCT> ORDER_PRODUCT { get; set; }
        public virtual PLATFORM PLATFORM { get; set; }
        public virtual PUBLISHER PUBLISHER { get; set; }
    }
}
