//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitricStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOFTWARE
    {
        public int IDSoft { get; set; }
        public string NameSoft { get; set; }
        public string Description { get; set; }
        public string Capacity { get; set; }
        public Nullable<int> IDCatSoft { get; set; }
        public Nullable<int> IDPublisher { get; set; }
        public Nullable<int> IDPlatform { get; set; }
        public Nullable<int> IDLanguage { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Rating { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string PicBG { get; set; }
        public string PicDetail1 { get; set; }
        public string PicDetail2 { get; set; }
        public string PicDetail3 { get; set; }
        public string PicDetail4 { get; set; }
    
        public virtual CATEGORY_SOFTWARE CATEGORY_SOFTWARE { get; set; }
        public virtual LANGUAGE LANGUAGE { get; set; }
        public virtual PLATFORM PLATFORM { get; set; }
        public virtual PUBLISHER PUBLISHER { get; set; }
    }
}
